---
title: "Adverse Events"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    theme: readable
    vertical_layout: fill
params:
  drug: Keytruda
---


```{r setup, include=FALSE}
library(flexdashboard)
library(stringr)
library(openfda)
library(dplyr)
library(ggplot2)
library(ggthemes)

get_adverse <- function(gender, brand_name, age) {
  fda_query("/drug/event.json") %>%
    fda_filter("patient.drug.openfda.brand_name", brand_name) %>% 
    fda_filter("patient.patientsex", gender) %>% 
    fda_filter("patient.patientonsetage", age) %>% 
    fda_count("patient.reaction.reactionmeddrapt.exact") %>% 
    fda_limit(10) %>% 
    fda_exec()
}

create_age <- function(min, max){#
  sprintf('[%d+TO+%d]', min, max)
}
```

```{r}

age <- create_age(20,65)

jnk <- capture.output(male <- get_adverse("1", params$drug, age))
if (!is.null(male)) {
  male$gender <- 'male'
}

jnk <- capture.output(female <- get_adverse("1", params$drug, age))
if (!is.null(female)) {
  female$gender <- 'female'
}

adverse <- rbind(male, female)

```

Column 
-----------------------------------------------------------------------

### All Events

```{r}
adverse %>% 
  group_by(term) %>% 
  summarise(count = sum(count)) %>% 
  ggplot() +
    geom_bar(aes(reorder(term,count), count), stat = 'identity') +
    coord_flip() +
    labs(
      title = params$drug,
      x = NULL,
      y = NULL
    ) +
    theme_minimal()
```



Column 
-----------------------------------------------------------------------

### Age Range

```{r}
age_label <- str_replace_all(age, fixed("+"), " ") %>% 
    str_replace(fixed("["), "") %>% 
    str_replace(fixed("]"), "") %>% 
    str_replace(fixed("TO"), "-")     

valueBox(age_label, icon = 'glyphicon-user')
```

### Events by Gender

```{r}
ggplot(adverse) +
    geom_bar(aes(reorder(term,count), count, fill = gender), stat = 'identity') +
    facet_wrap(~gender)+
    coord_flip() +
    labs(
      title = params$drug,
      x = NULL,
      y = NULL
    ) +
    theme_minimal() + 
    guides(fill = FALSE) + 
    scale_fill_manual(values = c("#d54a30","#4c83b6"))
```
