---
title: "ggplot2 AEs Explorer"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(tidyverse)
library(haven)
library(mgcv)
dataset <- read_sas("dmae.sas7bdat") %>% mutate(
    SEX = factor(SEX),
    AESEV =  factor(AESEV),
    RACE = factor(RACE)
)

data <- read_sas("dmae.sas7bdat") %>% mutate(
    SEX = factor(SEX),
    AESEV =  factor(AESEV),
    RACE = factor(RACE)
)

```


Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}

sliderInput('sampleSize', 'Sample Size', min=5, max=nrow(dataset),
            value=min(500, nrow(dataset)), step=200, round=0)

checkboxInput('jitter', 'Jitter', value = FALSE)
checkboxInput('smooth', 'Smooth', value = FALSE)

selectInput('x', 'X', names(dataset))
selectInput('y', 'Y', names(dataset), names(dataset)[[2]])
selectInput('color', 'Color', c('None', names(dataset)))

selectInput('facet_row', 'Facet Row',
            c(None='.', names(dataset[sapply(dataset, is.factor)])))
selectInput('facet_col', 'Facet Column',
            c(None='.', names(dataset[sapply(dataset, is.factor)])))
```

Outputs
-----------------------------------------------------------------------

### AEs

```{r}



dataset <- reactive({
  data[sample(nrow(data), input$sampleSize),]
})

renderPlot({
 
  p <- ggplot(dataset(), aes_string(x=input$x, y=input$y)) + geom_point()
  
  if (input$color != 'None')
    p <- p + aes_string(color=input$color)
  
  facets <- paste(input$facet_row, '~', input$facet_col)
  if (facets != '. ~ .')
    p <- p + facet_grid(facets)
  
  if (input$jitter)
    p <- p + geom_jitter()
  if (input$smooth)
    p <- p + geom_smooth()
  
  print(p)
})
```